apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: {{ include "demo-app.fullname" . }}-success-rate
  labels:
    {{- include "demo-app.labels" . | nindent 4 }}
spec:
  args:
  - name: service-name
  metrics:
  - name: success-rate
    interval: 1m
    count: 2
    successCondition: result[0] >= 0.99
    failureLimit: 2
    provider:
      prometheus:
        address: http://prometheus-server.monitoring.svc.cluster.local:80
        query: |
          (
            sum(rate(http_requests_total{status!~"5.*", app_kubernetes_io_instance="{{ include "demo-app.fullname" . }}"}[1m])) 
            / 
            (sum(rate(http_requests_total{app_kubernetes_io_instance="{{ include "demo-app.fullname" . }}"}[1m])) > 0)
          ) or vector(1)
