apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "demo-app.fullname" . }}
  labels:
    {{- include "demo-app.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: traefik-gateway
      namespace: traefik-system
  hostnames:
    - demo-app.local
  rules:
    - backendRefs:
        - name: {{ include "demo-app.fullname" . }}
          port: {{ .Values.service.port }}
          weight: 100
        - name: {{ include "demo-app.fullname" . }}-canary
          port: {{ .Values.service.port }}
          weight: 0
